#时钟约束
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

#IO引脚约束
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports ad_clk_1]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports ad_oe_1]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports ad_otr_1]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[0]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[1]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[2]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[3]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[4]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[5]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[6]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[7]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[8]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports {ad_data_1[9]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports ad_clk_2]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports ad_oe_2]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports ad_otr_2]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[0]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[1]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[2]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[3]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[4]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[5]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[6]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[7]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[8]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports {ad_data_2[9]}]