[Dialogs]
UserInfo=0
FeatureInfo1=1
SingleDirectory=1
InstallationType=0
FeatureTree=0
License=1
License2=0
NICertificate=0
ConfirmStart=1
End=1

[Distribution]
Title=1
GUID={1E90F3DD-A730-4D3B-8311-50338D14B166}
PackageGUID={CD65B494-ED06-4418-8065-4EE454FA982E}
Version=3.1.0
IDPath=nidist.id
Has64bitPart=1

[EndDialog]
Readme=5;30,50,330,150;static

[Files]
LicenseTextFile0009=NI;license\NI Released License Agreement - English.rtf
LicenseTextFile0010=NI;license\NI Released License Agreement - Spanish.rtf
LicenseTextFile0016=NI;license\NI Released License Agreement - Italian.rtf
LicenseTextFile0007=NI;license\NI Released License Agreement - German.rtf
LicenseTextFile0012=NI;license\NI Released License Agreement - French.rtf
LicenseTextFile0017=NI;license\NI Released License Agreement - Japanese.rtf
LicenseTextFile0018=NI;license\NI Released License Agreement - Korean.rtf
LicenseTextFile2052=NI;license\NI Released License Agreement - Simplified Chinese.rtf

[Graphics]
TopBar=IDB_TOPSTRIP,IDB_LARGETOPSTRIP
FullScreen=IDB_FULLSCREEN,IDB_LARGEFULLSCREEN

[InitProgress]
left=55
top=165
right=340
bottom=179
red=206
green=203
blue=173

[InstallLevels]
Default=100

[Localization]
Languages=9
ForceLanguage=9
CustomRes0009=supportfiles\customResource0009.dll

[Merged]
Path=supportfiles\merged.cab

[MsiEngine]
WinNTPath=supportfiles\WindowsInstaller-KB893803-v2-x86.exe
RequiredVersion=3.1.0.0
CommandLine=/passive /norestart

[OS]
VersionNTMin=5,0,2195,3,0
VersionNTMax=

[Settings]
WelcomeAutoAdvance=1

[SingleDirectoryDialog]
DirText1=4
DirText2=7
Dir1=INSTALLDIR.MDF100
Dir1EditLabel=8
Dir2=NIDIR
Dir2EditLabel=9

[Strings]
WelcomeTitle=2;15,20,260,45
WelcomeText=3;15,55,260,115

[Utilities]
UpgradeManagerPostProcessor=supportfiles\niPie.exe
NISysInfo=supportfiles\NISysInf.dll

[Parts]
lv85runtime.msi=
MetaUninstaller.msi=
MDFSupport.msi=
EulaDepot.msi=
svcloc.msi=
mkl.msi=
logos.msi=
logos64.msi=
tdms.msi=
tdms64.msi=
LVRTNBFIFO.msi=
LogosXT.msi=
LogosXT64.msi=
VC2008MSMs_x86.msi=
VC2008MSMs_x64.msi=
install.msi=
[lv85runtime.msi]
Path=bin\p8\lv85rte\lv85runtime.msi
Volume=1
ProductCode={065F29A4-D4D9-4BB9-85AF-8A878907BBD6}
ProductId={065F29A4-D4D9-4BB9-85AF-8A878907BBD6}
LangXfm0007=bin\p8\lv85rte\deu.mst
LangXfm0012=bin\p8\lv85rte\fra.mst
LangXfm0017=bin\p8\lv85rte\jpn.mst
LangXfm0018=bin\p8\lv85rte\kor.mst
LangXfm2052=bin\p8\lv85rte\chs.mst
[MetaUninstaller.msi]
Path=bin\p0\MU\MetaUninstaller.msi
Volume=1
ProductCode={0DFF0C5C-D82D-4C11-91AB-86411792D081}
ProductId={0DFF0C5C-D82D-4C11-91AB-86411792D081}
LangXfm0007=bin\p0\MU\MetaUninstaller.msi_deu.mst
LangXfm0012=bin\p0\MU\MetaUninstaller.msi_fra.mst
LangXfm0017=bin\p0\MU\MetaUninstaller.msi_jpn.mst
LangXfm0018=bin\p0\MU\MetaUninstaller.msi_kor.mst
LangXfm0019=bin\p0\MU\MetaUninstaller.msi_nld.mst
LangXfm1028=bin\p0\MU\MetaUninstaller.msi_cht.mst
LangXfm1030=bin\p0\MU\MetaUninstaller.msi_dan.mst
LangXfm1040=bin\p0\MU\MetaUninstaller.msi_ita.mst
LangXfm1044=bin\p0\MU\MetaUninstaller.msi_nor.mst
LangXfm1046=bin\p0\MU\MetaUninstaller.msi_ptb.mst
LangXfm1049=bin\p0\MU\MetaUninstaller.msi_rus.mst
LangXfm1053=bin\p0\MU\MetaUninstaller.msi_sve.mst
LangXfm2052=bin\p0\MU\MetaUninstaller.msi_chs.mst
LangXfm3082=bin\p0\MU\MetaUninstaller.msi_esn.mst
[MDFSupport.msi]
Path=bin\p7\MDF\MDFSupport.msi
Volume=1
ProductCode={BBA6DF34-EA20-4FFB-8440-1F9657643F79}
ProductId={BBA6DF34-EA20-4FFB-8440-1F9657643F79}
LangXfm0007=bin\p7\MDF\MDFSupport.msi_deu.mst
LangXfm0012=bin\p7\MDF\MDFSupport.msi_fra.mst
LangXfm0017=bin\p7\MDF\MDFSupport.msi_jpn.mst
LangXfm0018=bin\p7\MDF\MDFSupport.msi_kor.mst
LangXfm1028=bin\p7\MDF\MDFSupport.msi_cht.mst
LangXfm2052=bin\p7\MDF\MDFSupport.msi_chs.mst
[EulaDepot.msi]
Path=bin\p7\MDF\EulaDepot.msi
Volume=1
ProductCode={E6F385C0-79A1-44F0-9C15-70D1F2C74D01}
LangXfm0007=bin\p7\MDF\EulaDepot.msi_deu.mst
LangXfm0012=bin\p7\MDF\EulaDepot.msi_fra.mst
LangXfm0017=bin\p7\MDF\EulaDepot.msi_jpn.mst
LangXfm0018=bin\p7\MDF\EulaDepot.msi_kor.mst
LangXfm1028=bin\p7\MDF\EulaDepot.msi_cht.mst
LangXfm2052=bin\p7\MDF\EulaDepot.msi_chs.mst
[svcloc.msi]
Path=bin\p3\svcloc\svcloc.msi
Volume=1
ProductCode={07A99739-82EE-4537-AF2E-1607015D9992}
ProductId={07A99739-82EE-4537-AF2E-1607015D9992}
LangXfm0007=bin\p3\svcloc\deu.mst
LangXfm0012=bin\p3\svcloc\fra.mst
LangXfm0017=bin\p3\svcloc\jpn.mst
LangXfm0018=bin\p3\svcloc\kor.mst
LangXfm2052=bin\p3\svcloc\chs.mst
[mkl.msi]
Path=bin\p6\MKL700\mkl.msi
Volume=1
ProductCode={DB2C5648-700D-4AEF-83E1-70C72F0C34FA}
ProductId={DB2C5648-700D-4AEF-83E1-70C72F0C34FA}
LangXfm0007=bin\p6\MKL700\deu.mst
LangXfm0012=bin\p6\MKL700\fra.mst
LangXfm0017=bin\p6\MKL700\jpn.mst
LangXfm0018=bin\p6\MKL700\kor.mst
[logos.msi]
Path=bin\p9\logos.msi
Volume=1
ProductCode={04104DFE-C4F4-4A67-A172-4C495489E109}
ProductId={04104DFE-C4F4-4A67-A172-4C495489E109}
LangXfm0007=bin\p9\logos_deu.mst
LangXfm0012=bin\p9\logos_fra.mst
LangXfm0017=bin\p9\logos_jpn.mst
LangXfm0018=bin\p9\logos_kor.mst
LangXfm2052=bin\p9\logos_chs.mst
[logos64.msi]
Path=bin\p9\logos64.msi
Volume=1
ProductCode={B2000AA8-188C-4111-A334-3BDC10858693}
LangXfm0007=bin\p9\logos64_deu.mst
LangXfm0012=bin\p9\logos64_fra.mst
LangXfm0017=bin\p9\logos64_jpn.mst
LangXfm0018=bin\p9\logos64_kor.mst
LangXfm2052=bin\p9\logos64_chs.mst
[tdms.msi]
Path=bin\p5\tdms.msi
Volume=1
ProductCode={3DAA4182-08B7-45D9-8620-6B0E13018670}
ProductId={3DAA4182-08B7-45D9-8620-6B0E13018670}
LangXfm0007=bin\p5\tdms_deu.mst
LangXfm0012=bin\p5\tdms_fra.mst
LangXfm0017=bin\p5\tdms_jpn.mst
LangXfm0018=bin\p5\tdms_kor.mst
LangXfm2052=bin\p5\tdms_chs.mst
[tdms64.msi]
Path=bin\p5\tdms64.msi
Volume=1
ProductCode={65CBBF0F-F891-4F33-860C-C75E963653A2}
LangXfm0007=bin\p5\tdms64_deu.mst
LangXfm0012=bin\p5\tdms64_fra.mst
LangXfm0017=bin\p5\tdms64_jpn.mst
LangXfm0018=bin\p5\tdms64_kor.mst
LangXfm2052=bin\p5\tdms64_chs.mst
[LVRTNBFIFO.msi]
Path=bin\p2\LVRTNBFIFO\LVRTNBFIFO.msi
Volume=1
ProductCode={6E605604-E2CE-4331-AA19-5FEF273F3CFD}
ProductId={6E605604-E2CE-4331-AA19-5FEF273F3CFD}
LangXfm0007=bin\p2\LVRTNBFIFO\deu.mst
LangXfm0012=bin\p2\LVRTNBFIFO\fra.mst
LangXfm0017=bin\p2\LVRTNBFIFO\jpn.mst
LangXfm0018=bin\p2\LVRTNBFIFO\kor.mst
LangXfm2052=bin\p2\LVRTNBFIFO\chs.mst
[LogosXT.msi]
Path=bin\p4\LogosXT.msi
Volume=1
ProductCode={CFF55EAB-5A2F-4A95-99D4-EF3E585F03FD}
ProductId={CFF55EAB-5A2F-4A95-99D4-EF3E585F03FD}
LangXfm0007=bin\p4\LOGOS_XT_deu.mst
LangXfm0012=bin\p4\LOGOS_XT_fra.mst
LangXfm0017=bin\p4\LOGOS_XT_jpn.mst
LangXfm0018=bin\p4\LOGOS_XT_kor.mst
LangXfm2052=bin\p4\LOGOS_XT_chs.mst
[LogosXT64.msi]
Path=bin\p4\LogosXT64.msi
Volume=1
ProductCode={C342A5D7-9D75-4D37-879A-BAA68D168670}
LangXfm0007=bin\p4\LOGOS64_XT_deu.mst
LangXfm0012=bin\p4\LOGOS64_XT_fra.mst
LangXfm0017=bin\p4\LOGOS64_XT_jpn.mst
LangXfm0018=bin\p4\LOGOS64_XT_kor.mst
LangXfm2052=bin\p4\LOGOS64_XT_chs.mst
[VC2008MSMs_x86.msi]
Path=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi
Volume=1
ProductCode={4219AAB9-43BA-4085-8A42-78644B9F96D2}
ProductId={4219AAB9-43BA-4085-8A42-78644B9F96D2}
LangXfm0007=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi_deu.mst
LangXfm0012=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi_fra.mst
LangXfm0017=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi_jpn.mst
LangXfm0018=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi_kor.mst
LangXfm1028=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi_cht.mst
LangXfm2052=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi_chs.mst
[VC2008MSMs_x64.msi]
Path=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi
Volume=1
ProductCode={F239D27C-73AE-4665-9F05-DAABD1902AC1}
LangXfm0007=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi_deu.mst
LangXfm0012=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi_fra.mst
LangXfm0017=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi_jpn.mst
LangXfm0018=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi_kor.mst
LangXfm1028=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi_cht.mst
LangXfm2052=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi_chs.mst
[install.msi]
Path=bin\dp\install.msi
Volume=1
ProductCode={C26B1104-6E04-4CE3-A799-B75946DB7FF3}
ProductId={C26B1104-6E04-4CE3-A799-B75946DB7FF3}
[LicenseTypes]
LicenseType1=NIStandardReleased
LicenseType2=XercesLicense27
LicenseType3=XercesNotice27
[SilentInstallRequirements]
MustAcceptLicenses=1
[MDF]
MDFVersion=2.7.1.128
HasPatchSupport=0
DevPartSection=install.msi
