# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mizar_ps/mizar_ps.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mizar_ps || ORIG_REF_NAME==mizar_ps} -quiet] -quiet

# IP: bd/mizar_ps/ip/mizar_ps_processing_system7_0_0/mizar_ps_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mizar_ps_processing_system7_0_0 || ORIG_REF_NAME==mizar_ps_processing_system7_0_0} -quiet] -quiet

# XDC: e:/Apollo_LCD/zynq_boot_support/zynq_boot_support.gen/sources_1/bd/mizar_ps/ip/mizar_ps_processing_system7_0_0/mizar_ps_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mizar_ps_processing_system7_0_0 || ORIG_REF_NAME==mizar_ps_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Apollo_LCD/zynq_boot_support/zynq_boot_support.gen/sources_1/bd/mizar_ps/mizar_ps_ooc.xdc
